### ISSUE TITLE
Cannot uglify anymore after recent update

### ISSUE THREAD

**Issue by lemoustachiste** [tylingsoft/graphlibrary#1]
Hi, I am using mermaid in my project, which is using dagre-layout which is using this project.
It seems with a recent change, running uglify does not work anymore in my project.

This is the ouput received:
```
ERROR in 0.bundle.js from UglifyJs
SyntaxError: Unexpected token: name (v) [./~/dagre-layout/~/graphlibrary/lib/graph.js:363,0]
```

I have manually tried the various versions, and it works up until version 2.1.6, so I'd say this commit is the culprit? https://github.com/tylingsoft/graphlibrary/commit/557fc953e29b572d35fe22d510fa52e18824c923

Is this something you could take a look at? 

Thanks

**Comment by lemoustachiste** [comment]
hacked at project level

**Comment by tylerlong** [comment]
Could you please try to replace `uglify-js` with `uglify-es` in your own project?

**Comment by lemoustachiste** [comment]
@tylerlong yes, that's what I did in the end.
